print "You can't touch this"
print "You can't touch this"
print "You can't touch this"
print "You can't touch this"
print "You can't touch this"
print " "
print "My, my, my music hits me so hard"
print "Makes me say Oh, my Lord"
print "Thank you for blessing me"
print "With a mind to rhyme and two hype feet"
print " "
print "It feels good, when you know you're down"
print "A super dope homeboy from the Oak town"
print "And I'm known as such"
print "And this is a beat, uh, you can't touch"
print " "
print "I told you, homeboy"
print "(You can't touch this)"
print "Yeah, that's how we living and you know"
print "(You can't touch this)"
print " "
print "Look at my eyes, man"
print "(You can't touch this)"
print "Yo, let me bust the funky lyrics"
print "(You can't touch this)"
print " "
print "Fresh new kicks, advance"
print "You gotta like that, now, you know you wanna dance"
print "So move, outta your seat"
print "And get a fly girl and catch this beat"
print " "
print "While it's rolling', hold on"
print "Pump a little bit and let 'em know it's going' on"
print "Like that, like that"
print " "
print "Cold on a mission so fall them back"
print "Let 'em know, that you're too much"
print "And this is a beat, uh, you can't touch"
print " "
print "Yo, I told you"
print "(You can't touch this)"
print "Why you standing' there, man?"
print "(You can't touch this)"
print "Yo, sound the bell, school is in, sucking"
print "(You can't touch this)"
print " "
print "Give me a song or rhythm"
print "Making' 'em sweat, that's what I'm giving' 'em"
print "Now, they know"
print "You talking' about the Hammer, you talking' about a show"
print " "
print "That's hype and tight"
print "Singers are sweating' so pass them a wipe"
print "Or a tape, to learn"
print "What's it gonna take in the nineties to burn"
print " "
print "The charts? Legit"
print "Either work hard or you might as well quit"
print "That's word because you know"
print "You can't touch this, you can't touch this"
print " "
print "Break it down"
print "Stop, Hammer time"
print " "
print "Go with the funk, it is said"
print "If you can't groove to this"
print "Then you probably are dead"
print " "
print "So wave your hands in the air"
print "Bust a few moves"
print "Run your fingers through your hair"
print " "
print "This is it, for a winner"
print "Dance to this and you're gonna get thinner"
print "Move, slide your rump"
print "Just for a minute let's all do the bump, bump, bump"
print " "
print "Yeah"
print "(You can't touch this)"
print "Look, man"
print "(You can't touch this)"
print " "
print "You better get hype, boy"
print "Because you know you can't"
print "(You can't touch this)"
print "Ring the bell, school's back in"
print " "
print "Break it down"
print "Stop, Hammer time"
print " "
print "You can't touch this"
print "You can't touch this"
print "You can't touch this"
print " "
print "Break it down"
print "Stop, Hammer time"
print " "
print "Every time you see me"
print "The Hammer's just so hype"
print "I'm dope on the floor and I'm magic on the mic"
print " "
print "Now why would I ever stop doing this?"
print "With others making' records that just don't hit"
print "I've toured around the world, from London to the Bay"
print "It's Hammer, go Hammer, MC Hammer, yo, Hammer"
print "And the rest can go and play"
print " "
print "You can't touch this"
print "You can't touch this"
print "You can't touch this"
print " "
print "Yeah, you can't touch this"
print "I told you, you can't touch this"
print "Too hype, can't touch this"
print "Get way outta here, you can't touch this"
